name: Continuous Integration
on:
  pull_request:
  push:
    branches:
      - master
  workflow_dispatch:


jobs:
  build_maui:
    name: Build MAUI for Windows App
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 7.x.x
      - name: Install MAUI workload
        run: dotnet workload install maui
      - name: Restore
        run: dotnet restore /p:PublishReadyToRun=true
      - name: Build
        run: dotnet build DotaPlayerData.UI/DotaPlayerData.UI.csproj --no-restore -c Release -f:net7.0-windows10.0.19041.0
      - name: Test
        run: dotnet test --nologo 